# Generated by Django 4.0.6 on 2022-07-10 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 7, 10)),
        ),
    ]
