# Generated by Django 4.0.6 on 2022-07-13 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_layout_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='configuration',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='layout',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 7, 12)),
        ),
    ]
