# Generated by Django 4.0.6 on 2022-07-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_layout_configuration_alter_layout_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='configuration',
            field=models.JSONField(default=list, null=True),
        ),
    ]
