# Generated by Django 4.0.6 on 2022-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_layout_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='configuration',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
